### ISSUE TITLE
set custom controlserver

### ISSUE THREAD

**Issue by PlexSheep** [f-koehler/KTailctl#104]
Perhaps I missed it, but it would be amazing if we could specify a custom control server. I selfhost headscale to access my tailnet, so this tool isn't of much use to me otherwise.

**Comment by f-koehler** [comment]
I see. The thing is: the control server server is normally set with `tailscale login --login-server your-server.com`. It is coupled to that login and cannot be changed afterwards. You would have do a login with a different control server.

Currently, KTailctl does not handle the login process and assumes that you have logged via the CLI (it is planned, see #5, but I have not gotten around to it yet). In your case something like `tailscale login --operator=yourusername --login-server your-server.com`. Does the GUI work afterwards?

**Comment by PlexSheep** [comment]
After having set up my client like this:
```bash
#!/bin/bash
tailscale up \
--timeout 30s \
--login-server https://my.server.de \
```
It seems to work just fine.

**Comment by f-koehler** [comment]
> After having set up my client like this:
> 
> ```shell
> #!/bin/bash
> tailscale up \
> --timeout 30s \
> --login-server https://my.server.de \
> ```
> 
> It seems to work just fine.

Nice, I will definitely try to implement the login process at some point. But I guess I can close this issue for now.
