### ISSUE TITLE
Taildrop send files not working

### ISSUE THREAD

**Issue by aaylnx** [f-koehler/KTailctl#20]
Thanks so much for  your work on KTailctl. Today I am trying out sending files for the first time and am running into problems.

My system: Fedora Kinoite 38
Tailscale version: 1.44
KTailctl version: 0.42

When trying to send files I get the following error

```
Access denied: file access denied
Bytes sent 163840
Bytes sent 163840
Bytes sent 163840
Bytes sent 163840
Bytes sent 163840
```

Bytes sent keeps repeating.

I have made sure to give the flatpak version of KTailctl file access permissions using Flatseal.  In fact here are my flatpak permissions for KTailctl

````
flatpak info --show-permissions org.fkoehler.KTailctl
[Context]
shared=network;ipc;
sockets=x11;wayland;session-bus;system-bus;fallback-x11;
devices=dri;
features=canbus;
filesystems=home;/run/tailscale:ro;host-os;xdg-config/kdeglobals:ro;host;host-etc;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
org.kde.kconfig.notify=talk
org.kde.KGlobalSettings=talk
org.kde.StatusNotifierWatcher=talk

````

Any thoughts?

Thanks!

**Comment by aaylnx** [comment]
Followup

`sudo tailscale up --operator=$USER`

Fixed things. Thanks again for the good work on this!

**Comment by f-koehler** [comment]
Thanks for the report! Indeed you have to be the operator of tailscale which you achieved with the command above. I am aware this and probably make this more clear. I plan to add some info in the `README.md`, on the flathub page and make it also clear in the GUI itself!

**Comment by f-koehler** [comment]
@aaylnx v0.5.0 adresses this issue and should appear on flathub in the next hours.

**Comment by aaylnx** [comment]
> @aaylnx v0.5.0 adresses this issue and should appear on flathub in the next hours.

This is awesome. Thanks!
