### ISSUE TITLE
Test tailscale send

### ISSUE THREAD

**Issue by f-koehler** [f-koehler/KTailctl#201]
I have not tested this feature in quite a while and it seems a bit borked atm (#187). It probably could also use some refactoring.

**Comment by oldman20** [comment]
> i cant see files sent from others device, it just say success on others device but cant see file on /home/my-user-name/Downloads/taildrop
> And i can sent file from machine installed kTailctl. Dont know why? I tried set location received files and restart service, even restart machine. Nothing work!
> and strange: taildrop directory not create automatic, i tried created it manual and trying sent file, client said success but cant file it on machine kTailctl?

> after research, i found default location received files is /var/lib/tailscale/files/ and found files which i sent above. So i think default location set in kTailctl ís not work. Maybe it is bug? anyone has same issue?

@f-koehler Today i tried again but seem nothing new? still cant set locate for save files?

**Comment by f-koehler** [comment]
This is because I did not have time to work on this so far. Yesterday, I looked into the sending of files which I fixed in `main` (see this PR: https://github.com/f-koehler/KTailctl/pull/283). Next, I will tackle the receiver code which is broken atm before releasing a new version.

**Comment by oldman20** [comment]
thank so much and please keep your great work. many thank!

**Comment by f-koehler** [comment]
I will tackle the receiver in another version. I will release `v0.18.0` that has a fixed send functionality.
