### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [f-koehler/KTailctl#267]
Since I've updated to the latest version of KTailctl, I've noticed that the app's memory usage is radically higher than it has any right to be. Sitting at idle, with no traffic going through tailscale, after being open for about an hour, it's already using more RAM than Microsoft Edge is with 34 tabs open.

![image](https://github.com/f-koehler/KTailctl/assets/102361830/cd81929a-9ac1-4ddc-9bb5-a63247a8f0f1)

I'm on Arch Linux, and here's the `About KTailctl` page.  
![image](https://github.com/f-koehler/KTailctl/assets/102361830/6c6945c8-46b2-4e06-9c3f-5252c6437ad4)

If you need any other information, please let me know.

**Comment by f-koehler** [comment]
You are right, that is definitely a bug. I refactored the whole backend in the latest version and probably introduced this regression...

**Comment by f-koehler** [comment]
@SeaswimmerTheFsh, I reproduced the issue locally and resolved it in `v0.17.1` which will take a few hours to propagate to flathub. If you are in a hurry you can install the latest test build from the flathub PR: https://github.com/flathub/org.fkoehler.KTailctl/pull/36

Sorry for any inconvenience caused!

Note to self, even though there are no other severe leaks visible I should take a closer look soon.
