### ISSUE TITLE
flatpak crashing (seg fault) on fedora aurora (atomic)

### ISSUE THREAD

**Issue by blackjack419** [f-koehler/KTailctl#285]
Installed flatpak from flathub on fedora aurora (Universal blue) and am getting a segfault. 

I'm running the flatpak with the following command (default .desktop command):
```
flatpak run --branch=stable --arch=x86_64 --command=ktailctl org.fkoehler.KTailctl
```

When run from the command line, the error printed out is: 
```
[2024-09-15T22:59:56][critical][/run/build/ktailctl/src/wrapper/logging.cpp:10] failed to suggest exit node: no preferred DERP, try again later
```

```
           PID: 11256 (ktailctl)
           UID: 1000 (xxx)
           GID: 1000 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-09-15 23:07:03 EDT (11s ago)
  Command Line: ktailctl
    Executable: /app/bin/ktailctl
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-org.fkoehler.KTailctl-11245.scope
          Unit: user@1000.service
     User Unit: app-flatpak-org.fkoehler.KTailctl-11245.scope
         Slice: user-1000.slice
     Owner UID: 1000 (xxx)
       Boot ID: 1a37267a596346138c4fddbfee62cd5e
    Machine ID: b604da9a86ad42c49df666e08baa3a6a
      Hostname: xxx
       Storage: /var/lib/systemd/coredump/core.ktailctl.1000.1a37267a596346138c4fddbfee62cd5e.11256.1726456023000000.zst (present)
  Size on Disk: 5.1M
       Message: Process 11256 (ktailctl) of user 1000 dumped core.
                
                Module /app/bin/ktailctl without build-id.
                Module /app/bin/ktailctl
                Module /app/lib/libktailctl_config.so without build-id.
                Module /app/lib/libktailctl_config.so
                Module /app/lib/libktailctl_wrapper_logging.so without build-id.
                Stack trace of thread 2:
                #0  0x00007fc0a2c75b20 n/a (/usr/lib/x86_64-linux-gnu/libQt6Core.so.6.7.2 + 0x275b20)
                #1  0x0000559fe4421f1d n/a (/app/bin/ktailctl + 0x12f1d)
                #2  0x0000559fe442587c n/a (/app/bin/ktailctl + 0x1687c)
                #3  0x00007fc0a2be6d2e n/a (/usr/lib/x86_64-linux-gnu/libQt6Core.so.6.7.2 + 0x1e6d2e)
                #4  0x0000559fe4442587 n/a (/app/bin/ktailctl + 0x33587)
                #5  0x0000559fe442558e n/a (/app/bin/ktailctl + 0x1658e)
                #6  0x0000559fe4427733 n/a (/app/bin/ktailctl + 0x18733)
                #7  0x00007fc0a243b08a n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2808a)
                #8  0x00007fc0a243b14b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2814b)
                #9  0x0000559fe4421865 n/a (/app/bin/ktailctl + 0x12865)
                ELF object binary architecture: AMD x86-64

```

It does appear the segfault does not occur if running as root (sudo). Is this a permission issue?

Thanks in advance.

**Comment by f-koehler** [comment]
@blackjack419, I would suspect some particularity of these atomic variants of Fedora. On "normal" distros, it works fine when run as a normal user. I will have to investigate.

**Comment by blackjack419** [comment]
I also want to add that the flatpak kTailctl does come pre-installed on a fresh Ublue (bluefin or aurora) install and presumably works. I initially removed it because I didn't know what tailscale was at the time, but upon  learning about it I decided I wanted to try it again. So I redownload the flatpak and then hit this error.

**Comment by f-koehler** [comment]
> I also want to add that the flatpak kTailctl does come pre-installed on a fresh Ublue (bluefin or aurora) install and presumably works. I initially removed it because I didn't know what tailscale was at the time, but upon learning about it I decided I wanted to try it again. So I redownload the flatpak and then hit this error.
> 
> I ensured that I set my username to the tailscale operator, but note that I did not have any tailscale remote configured. I believe this gui should work regardless of it tailscale is actively up, right?

Wow, that is cool hear that it ships on Ublue! I did not know that.

When you say that you have no tailscale remote configured, does it mean that you did not run the `tailscale login`? If that is the case than KTailctl can crash as reported by another user: https://github.com/flathub/org.fkoehler.KTailctl/issues/39

I really need to get around to handling this situation (https://github.com/f-koehler/KTailctl/issues/5)

**Comment by f-koehler** [comment]
Just tested with flatpak test build and confirmed fix. `v0.18.0` should be on flathub in a few hours.
