### ISSUE TITLE
Crash when setting mullvad exit node from the systray icon menu.

### ISSUE THREAD

**Issue by inffy** [f-koehler/KTailctl#290]
I'm running CachyOS (Arch Linux) and noticed that if I try to set Mullvad exit node throug the icon menu - exit nodes -> select country and then exit node ktailctl just crashes. Tried running from cli and all i get is

> ❯ ktailctl
> [2024-09-26T16:30:52][warning][qrc:Peers.qml:10] qrc:Peers.qml:10:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
> [2024-09-26T16:30:52][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight"
> [2024-09-26T16:30:52][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value"
> [2024-09-26T16:30:52][warning][qrc:Statistics.qml:22] qrc:Statistics.qml:22: TypeError: Cannot read property 'totalUpSpeed' of undefined
> [2024-09-26T16:30:52][warning][qrc:Statistics.qml:27] qrc:Statistics.qml:27: TypeError: Cannot read property 'totalDownSpeed' of undefined
> [2024-09-26T16:31:02][info][/home/juha/.cache/paru/clone/ktailctl/src/KTailctl/src/wrapper/logging.cpp:18] set exit node to 100.78.117.133
> [1]    31250 segmentation fault (core dumped)  ktailctl

But if I open the GUI and go through there it works fine and exit node is set:

> ❯ ktailctl
> [2024-09-26T16:34:51][warning][qrc:Peers.qml:10] qrc:Peers.qml:10:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
> [2024-09-26T16:34:51][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight"
> [2024-09-26T16:34:51][warning][qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401] qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value"
> [2024-09-26T16:34:51][warning][qrc:Statistics.qml:22] qrc:Statistics.qml:22: TypeError: Cannot read property 'totalUpSpeed' of undefined
> [2024-09-26T16:34:51][warning][qrc:Statistics.qml:27] qrc:Statistics.qml:27: TypeError: Cannot read property 'totalDownSpeed' of undefined
> [2024-09-26T16:34:55][warning][file:///usr/lib/qt6/qml/org/kde/kirigami/ScrollablePage.qml:179] file:///usr/lib/qt6/qml/org/kde/kirigami/ScrollablePage.qml:179:9: QML MouseArea: Binding loop detected for property "implicitHeight"
> [2024-09-26T16:34:55][warning][file:///usr/lib/qt6/qml/org/kde/kirigami/ScrollablePage.qml:179] file:///usr/lib/qt6/qml/org/kde/kirigami/ScrollablePage.qml:179:9: QML MouseArea: Binding loop detected for property "implicitHeight"
> [2024-09-26T16:34:59][warning][qrc:ExitNodes.qml:12] qrc:ExitNodes.qml:12:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
> [2024-09-26T16:35:03][info][/home/juha/.cache/paru/clone/ktailctl/src/KTailctl/src/wrapper/logging.cpp:18] set exit node to
> [2024-09-26T16:35:08][warning][file:///usr/lib/qt6/qml/org/kde/kirigami/PageRow.qml:1098] file:///usr/lib/qt6/qml/org/kde/kirigami/PageRow.qml:1098:5: QML RowLayout: StackView has detected conflicting anchors. Transitions may not execute properly.
> [2024-09-26T16:35:18][info][/home/juha/.cache/paru/clone/ktailctl/src/KTailctl/src/wrapper/logging.cpp:18] set exit node to 100.78.113.70

If there is other logs somewhere that would show more info let me know

**Comment by f-koehler** [comment]
Just confirmed on my end. Does not occur for self-hosted exit nodes.

**Comment by f-koehler** [comment]
I isolated the issue which is fixed in PR #292. I am hoping to release a new version `0.18.0` in the next few days and it will definitely include this fix.
