### ISSUE TITLE
Clicking on recommendations or exit node on a list does nothing.

### ISSUE THREAD

**Issue by artur9010** [f-koehler/KTailctl#300]
![image](https://github.com/user-attachments/assets/3612ec00-9be2-4e78-ae3e-f8dc7d6f66ee)

On this page I can disconnect, but clicking on any node or "connect to recommended" does nothing while suggesting it should do something (it's clickable).

v0.18.0 from flathub, running on fedora

**Comment by f-koehler** [comment]
Thanks for the report! I confirmed the problem locally. It is a regression introduced by #292. It seems I tested setting the exit node via DNS name only for Mullvad nodes which works as it also corresponds to their basename.

**Comment by f-koehler** [comment]
Fixed in `v0.18.1` which will be on flathub in a few hours.
