### ISSUE TITLE
Feature: A toggle to allow exit node lan access

### ISSUE THREAD

**Issue by code8buster** [f-koehler/KTailctl#317]
A nice enhancement would be the ability to toggle LAN access on and off in the Settings or Exit nodes tab.

**Comment by f-koehler** [comment]
Definitely! I think it used to be there but it seems I might have removed it during some refactoring. I will add it back to the settings page in the exit node page.

**Comment by f-koehler** [comment]
Implemented in #333, thanks @code8buster
