### ISSUE TITLE
Display last used exit node in addition to suggested exit node

### ISSUE THREAD

**Issue by mankoff** [f-koehler/KTailctl#322]
I have a few exit nodes. One is selected. How do I default to another?

**Comment by f-koehler** [comment]
The suggested exit node is determined automatically. I have not checked on the actual implementation, it is provided by Tailscale itself but I assume that is based on latency or geographic information.

I added it as a quick way to switch to this recommended exit node. You should be able to select your exit nodes from the exit node menu (either tray icon or exit node page).

I am not sure why you would want to change this? Would you like to have another exit node displayed as well (e.g. the most recently used one or a favourite one)?

**Comment by mankoff** [comment]
Good to know that this is just reporting a tailscale suggestion.

I have two Pi in my home, both as exit nodes. One is a Pi 3 (slow) and one is a Pi 5 (fast). It usually suggests the Pi 3 for some reason, I prefer the Pi 5.

**Comment by f-koehler** [comment]
I see. I think it could make sense to additionally display the last used exit node in addition to the suggested by Tailscale itself. That should suit your use case, right?

**Comment by mankoff** [comment]
Yes that would suit my use-case.
