### ISSUE TITLE
"Report a bug" redirects to KDE bug tracker

### ISSUE THREAD

**Issue by perroboc** [f-koehler/KTailctl#33]
When I click on "Report a bug" from the "About KTailctl" screen, I get redirected to https://bugs.kde.org/enter_bug.cgi?format=guided&product=KTailctl&version=v0.7.0

Shoudln't it redirect here?

**Comment by f-koehler** [comment]
Yes, it should. The redirection to bugs.kde.org is due to the defaults of the Official Kirigami App template. I will make sure to change this (I will check the other links on the about page as well), thanks!

**Comment by f-koehler** [comment]
Fixed in #39 (will be in next release)
