### ISSUE TITLE
[Feature Request] Add ability to chose an exit node

### ISSUE THREAD

**Issue by Justinzobel** [f-koehler/KTailctl#35]
I see there's an Exit Node Setting but I assume that's to set the current device as an Exit Node.

**Comment by f-koehler** [comment]
@Justinzobel Your observation is correct. I have never really used this feature of tailscale but agree that it should be put into place. Starting in a few weeks I will have some time for KTailctl again and see what I can do :)

**Comment by f-koehler** [comment]
Implemented in v0.9.0.
