### ISSUE TITLE
Crashing after enabling Mullvad

### ISSUE THREAD

**Issue by russellmilliner** [f-koehler/KTailctl#43]
I use the flatpak version, and ever since I've enabled Mullvad, the app is constantly crashing.  Frequently it crashes even on startup.  It may be related to all of the Mullvad exit-nodes are appearing as peers in the list.  Attached is the output till crash
[ktailctl.txt](https://github.com/f-koehler/KTailctl/files/12602533/ktailctl.txt)

**Comment by f-koehler** [comment]
That is sad to hear and thanks for the log. I have not tried this feature yet. As I understand one cannot use an existing Mullvad account, right? (I happen to have one)

**Comment by russellmilliner** [comment]
I don't believe you can use an existing account, but it is only $5/mo and can cancel at any time.  When you sign up, it is prorated to the end of the month, so if you signed up today, it would only be about $2.50.

**Comment by f-koehler** [comment]
My Mullvad subscription is running out soon, so I will probably also switch to this new tailscale feature. But first, I will finish implementing the feature of setting the exit node in KTailctl. Then I will debug this problem and also check if we could have the Mullvad exit nodes in KTailctl.

**Comment by f-koehler** [comment]
v0.9.0 should appear on flathub in a few hours which is compiled against a newer version of the tailscale library. Thus, it might resolve this issue. Can you test again before I sink time into reproducing this issue?

**Comment by russellmilliner** [comment]
> v0.9.0 should appear on flathub in a few hours which is compiled against a newer version of the tailscale library. Thus, it might resolve this issue. Can you test again before I sink time into reproducing this issue?

Will do!

**Comment by russellmilliner** [comment]
> > v0.9.0 should appear on flathub in a few hours which is compiled against a newer version of the tailscale library. Thus, it might resolve this issue. Can you test again before I sink time into reproducing this issue?
> 
> Will do!

no joy with v0.9.0-dirty.  Let me know if you need the full stack trace details

flatpak run org.fkoehler.KTailctl
Qt: Session management error: Could not open network socket
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: "@title"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "GUI for tailscale on the KDE Plasma desktop" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "(c) 2023" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Fabian K\xC3\xB6hler" msgid_plural: "" msgctxt: "@info:credit"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Project Maintainer" msgid_plural: "" msgctxt: "@info:credit"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Peers" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Quit" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "About KTailctl" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Settings" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Statistics" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Peers" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: ""
runtime: pointer 0xc0002da000 to unallocated span span.base()=0xc0002da000 span.limit=0xc000330000 span.state=0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

**Comment by f-koehler** [comment]
@russellmilliner  That is a bummer! I just added the Mullvad extension to my account and was able to reproduce the issue. I already got some idea which part of the code is causing the problem and will keep you posted as I investigate.

**Comment by f-koehler** [comment]
@russellmilliner I fixed this bug in version 0.9.2 which should appear on flathub in the next few hours. Let me know if the problem persists on your end, I am going to close the issue for now.

Enabling the Mullvad feature adds loads of peers to the peer list. I am planning to make some interface changes in the next version `v0.10.0` to accommodate for this behavior and make the GUI more usable.

Memo to self: The issue was the handling of strings that were returned to the C code. The strings were allocated on the Go side and then passed to C++ where they were handled as `GoString` types. However, Go is a garbage-collected language. The increased number of peers triggered the garbage collection which caused pointer issues. The fix is to return char pointers that are created using `C.CString`. However, this memory has to be manually deallocated using `free`.

**Comment by russellmilliner** [comment]
Just to respond that it is working well now.  

Also, as you said, a filter checkbox to turn off mullvad clients would be nice.  Maybe a search/filter box to show clients matching or not matching a wildcard or regex DNS.

Other suggestions:
Sorting
link/button to SSH to a host

**Comment by f-koehler** [comment]
> Just to respond that it is working well now.
> 
> Also, as you said, a filter checkbox to turn off mullvad clients would be nice. Maybe a search/filter box to show clients matching or not matching a wildcard or regex DNS.
> 
> Other suggestions: Sorting link/button to SSH to a host

Happy to hear that it works. I am already planning on adding filtering/sorting (see #53).

I really like the idea of a SSH button. Will try to also get it into the next version (see #56).
