### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by russellmilliner** [f-koehler/KTailctl#77]
Since version 0.10 and 0.11 using the Flathub version, I see continuously increasing memory usage for the katilctl process.

**Comment by f-koehler** [comment]
Thanks for the report. Would have expected that there might be some leaks, likely in the go wrapper. I will look into that.

**Comment by f-koehler** [comment]
There is definitely a memory leak and the amount of allocated memory grows linearly over time. Using `heaptrack` I was able to track it down to the JSON parsing. Right now it is not clear why this occurs and I will continue to investigate. Maybe QJson will have to be swapped out with something like nlohmann/json

**Comment by f-koehler** [comment]
@russellmilliner just to give you an update: I am working on this, it's a problem for me as well. However, I decided a substantial part of the code to simplify it and have more robust JSON parsin. I am hoping to release a new version in the next few days.

**Comment by f-koehler** [comment]
This is fixed in v0.12.0 which will appear on flathub in a few hours.
