### ISSUE TITLE
Taskbar Icon Exit node menu: Don't show Self-Hosted menu if no non-self-hosted nodes

### ISSUE THREAD

**Issue by j5155** [f-koehler/KTailctl#90]
![image](https://github.com/f-koehler/KTailctl/assets/54331556/474efb0f-c80d-4649-be38-bc3df351c1da)
This self-hosted menu is unnecessary for those that do not have any non-self hosted exit nodes. I assume it's there for easy Mullvad usage, but it bothers me just a tiny bit when it's not needed.

**Comment by f-koehler** [comment]
Great suggestion! Should be easy to fix.

**Comment by f-koehler** [comment]
@j5155 here is how I implemented it:
![ktailctl](https://github.com/f-koehler/KTailctl/assets/5512292/bf1590ea-208d-4c77-bf56-e4d79bce8d7a)
What do you think?

Was going to release this quickly as `v0.12.1` release but something changed in the go toolchain breaking the flatpak build. So I will delay this for a bit.

**Comment by f-koehler** [comment]
@j5155 v0.13.0 should be published on flathub in a few hours and contain this fix.
